version: '3.8'

services:
  postgres-dev:
    image: postgres:latest
    container_name: ra_backend_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ra_backend_dev
    ports:
      - "5433:5432"   # Host:Container
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: